# Generated by Django 3.1.6 on 2021-02-11 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentSketch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text', models.CharField(default='Комментарий', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Имя', max_length=30)),
                ('last_name', models.CharField(default='Фамилия', max_length=30)),
                ('adress', models.CharField(default='Адрес', max_length=100)),
                ('photo', models.ImageField(default='user_icon.png', upload_to='people_photos/')),
                ('rating', models.FloatField(default='5.0')),
                ('about', models.CharField(default='О себе', max_length=10000)),
                ('tegs', models.CharField(default='Стили', max_length=1000)),
                ('hello_word', models.CharField(default='Приветственное слово', max_length=2000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(default='адрес студии', max_length=200)),
                ('description', models.CharField(default='как добраться', max_length=1000)),
                ('up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culttattoo.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPlaceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='WorkPlaceImage/')),
                ('wp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culttattoo.workplace')),
            ],
        ),
        migrations.CreateModel(
            name='VideoUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culttattoo.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Sketch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default='0')),
                ('coments', models.ImageField(default='0', upload_to='')),
                ('label', models.CharField(default='Название товара', max_length=100, unique=True)),
                ('image', models.ImageField(default='', upload_to='item_image/')),
                ('UserProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseForMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='отзыв', max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='response_for_master_image/')),
                ('score', models.FloatField(default='5.0')),
                ('upmaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master', to='culttattoo.userprofile')),
                ('upuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentator', to='culttattoo.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LikeScketch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sketch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culttattoo.sketch')),
                ('up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culttattoo.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LikeCommentSketch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentSketch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culttattoo.commentsketch')),
                ('up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culttattoo.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='commentsketch',
            name='sketch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culttattoo.sketch'),
        ),
        migrations.AddField(
            model_name='commentsketch',
            name='up',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culttattoo.userprofile'),
        ),
    ]
